### ISSUE TITLE
IString should implement PartialOrd, Ord

### ISSUE THREAD

**Issue by ColonelThirtyTwo** [yewstack/implicit-clone#18]
str implements this - IString should as well. In particular, IStrings cannot be used as BTreeMap keys or BTreeSet items without this.

**Comment by cecton** [comment]
Ah yeah there are still a lot of impl missing. I have no bandwidth at the moment but feel free to open a PR

**Comment by kirillsemyonkin** [comment]
@ColonelThirtyTwo could you list some more traits that really need to be implemented? (those that won't do with a deref, for example BTree map keys/set items (because they need to be moved) need some traits to work (you listed them already), but `PartialEq<OsStr>` is probably fine to use via a deref, unless we agree that all/most `str`'s `impl`s should be transferred over)

**Comment by ColonelThirtyTwo** [comment]
@kirillsemyonkin I suggest looking at what `String` implements and going from there. I'd also add `serde::[De]Serialize` as well behind a feature gate.

**Comment by kirillsemyonkin** [comment]
> I'd also add `serde::[De]Serialize` as well

That has been added in #20.

> I suggest looking at what `String` implements and going from there

Yeah, that's what I've been saying, wondering if anyone else would read these comments and also leave their opinions on adding more than just `PartialOrd` and `Ord`
