### ISSUE TITLE
Usecases

### ISSUE THREAD

**Issue by SylvKT** [yewstack/implicit-clone#43]
I'm not sure what uses this library fills *exactly*. Could you elaborate further on potential uses and explain them?

**Comment by cecton** [comment]
Right now it is used in Yew as a way to distinguish types that can be cloned implicitly because they are cheap to clone (Rc, AttrValue, primitives, etc...) from those that implement clone but are not cheap to clone (Vec, things that allocate every time you clone...).

Feel free to re-open if this usecase and explanation isn't satisfactory for you.
